sdk: "/Users/Seaborg/.rvm/gems/ruby-1.8.7-p302@rails_2_3_8/gems/rhodes-3.1.0"
sdkversion: 3.1.0
name: speaky
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator4.2
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.speaky
  BundleURLScheme: speaky
wp:
  productid: 'xxx'
symbian:
    uid: '0xe56de5ef'

extensions: ["json", "another-extension"]
